In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [0],
              [1]])
x

array([[0],
       [0],
       [1]])

In [4]:
x

array([[0],
       [0],
       [1]])

In [1]:
# hitung nilai L2 norm dari vector x
(0**2 + 0**2 + 1**2)**(1/2)

1.0

2. buat vector v dengan elemen (3,4)

In [6]:
v = np.array([[3],
              [4]])
v

array([[3],
       [4]])

In [5]:
# hitung nilai L2 norm dari vector v
(3**2 + 4**2)**(1/2)

5.0

In [7]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(v)
unit_v = v / norm
unit_v

array([[0.6],
       [0.8]])

In [8]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_v)

np.float64(1.0)