In [2]:
import numpy as np

In [3]:
X_sym = np.array([[5, 0, 0], [0, 5, 0], [5, 0, 5]])
X_sym

array([[5, 0, 0],
       [0, 5, 0],
       [5, 0, 5]])

Baris ini membuat sebuah matriks $3 \times 3$ bernama X_sym.

diagonal utamanya berisi angka $5, 5, 5$. tetapi bisa dilihat elemen di pojok kiri bawah (baris 3, kolom 1) yang bernilai 5, sedangkan pasangannya di pojok kanan atas (baris 1, kolom 3) bernilai 0

In [4]:
X_sym.T

array([[5, 0, 5],
       [0, 5, 0],
       [0, 0, 5]])

Perintah .T akan memutar matriks (baris menjadi kolom).

In [5]:
X_sym.T == X_sym

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])

Logika: Matriks disebut Simetris hanya jika $A = A^T$.

Hasil Spesifik: Pada posisi indeks Python akan memberikan nilai False karena $0 \neq 5$.

Kesimpulan: Matriks ini BUKAN matriks simetris.

1.Identifikasi Ketidaksesuaian: "Setelah nilai diubah, matriks tersebut tidak lagi memenuhi syarat matriks simetris.

2."Berikan Contoh Angka: "Dalam matriks ini, elemen baris ke-3 kolom ke-1 adalah 5, tetapi elemen baris ke-1 kolom ke-3 adalah 0. Karena tidak bercermin secara identik terhadap diagonal utama, maka ia bukan simetris.

3."Hasil Operasi: "Secara kodingan, saat kita menjalankan X_sym.T == X_sym, hasilnya tidak akan True untuk semua elemen, melainkan ada beberapa posisi yang menghasilkan False."

In [6]:
import torch

In [7]:
I = torch.tensor([[5, 0, 0], [0, 5, 0], [0, 0, 5]])
I

tensor([[5, 0, 0],
        [0, 5, 0],
        [0, 0, 5]])

 Variabel I di sini merepresentasikan Matriks Identitas ($I$).

In [10]:
x_pt = torch.tensor([50, 5, 5])
x_pt

tensor([50,  5,  5])

Ini adalah sebuah vektor kolom (atau tensor 1D) yang berisi tiga angka: 50, 5, dan 5.

In [11]:
torch.matmul(I, x_pt)

tensor([250,  25,  25])

matmul adalah singkatan dari matrix multiplication. Baris ini mengkalikan matriks identitas (I) dengan vektor $x_{pt}$.

Hasilnya: Sesuai hukum aljabar linear, setiap matriks atau vektor yang dikalikan dengan Matriks Identitas akan menghasilkan dirinya sendiri ($Ix = x$). Jadi, output dari kodingan ini tetaplah [25, 2, 5].