# *MATRIKS MULTIPLICATION EXERCISES*

In [9]:
import torch

Baris ini berfungsi untuk memanggil library PyTorch. PyTorch adalah framework open-source yang sering digunakan untuk pengembangan Deep Learning.


In [10]:
M_q = torch.tensor([[2, 5, 5], [0, 6, 1], [0, 0, 5]])
M_q

tensor([[2, 5, 5],
        [0, 6, 1],
        [0, 0, 5]])

Baris ini membuat sebuah Tensor 2-Dimensi (Matriks) berukuran $3 \times 3$ dengan nama variabel

M_q di bawahnya berfungsi untuk menampilkan isi dari matriks tersebut ke layar.

In [11]:
V_q = torch.tensor([[ 2, 5, 5], [0, 6, 1]]).T
V_q

tensor([[2, 0],
        [5, 6],
        [5, 1]])

Kode ini membuat sebuah tensor awal berukuran 2 X 3 (2 baris, 3 kolom), namun langsung diikuti oleh fungsi

Fungsi .T (Transpose): Digunakan untuk menukar posisi baris menjadi kolom.

Hasil Akhir: Matriks yang tadinya 2
X 3 berubah menjadi 3 X 2.

 aljabar linear  dimensi matriks sesuai untuk dikalikan dengan M_q

In [12]:
torch.matmul(M_q, V_q)

tensor([[54, 35],
        [35, 37],
        [25,  5]])

Fungsi torch.matmul() digunakan untuk melakukan perkalian matrik


 M_q berukuran ($3 \times 3$) dan v_q berukuran ($3 \times 2$).Karena jumlah kolom matriks pertama (3) sama dengan jumlah baris matriks kedua (3), maka perkalian ini sah/bisa dilakukan.

Komputer akan mengalikan baris dari M_q dengan kolom dari v_q satu per satu.

Output: Hasil akhirnya akan berupa matriks baru dengan ukuran $3 \times 2$.