In [5]:
import numpy as np

Matrix Inversion

1. buat matrix X ukuran 2x2 menggunakan numpy

In [6]:
# Membuat matriks X ukuran 2x2
X = np.array([[1, 2],
              [3, 4]])

print(X)

[[1 2]
 [3 4]]


In [8]:
# Matriks X
X = np.array([[1, 2],
              [3, 4]])

# Invers matriks X
Xinv = np.linalg.inv(X)

print(Xinv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# Matriks X
X = np.array([[1, 2],
              [3, 4]])

# Invers X
Xinv = np.linalg.inv(X)

# Perkalian X dengan Xinv
hasil = np.dot(X, Xinv)

print(hasil)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


2. selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch

In [12]:
#numpy

A = np.array([[4, 2],
              [5, -3]])

B = np.array([[4],
              [-7]])

X = np.linalg.inv(A) @ B
print(X)

[[-0.09090909]
 [ 2.18181818]]


In [22]:
import torch

In [23]:
#pytorch

A = torch.tensor([[4., 2.],
                  [5., -3.]])

B = torch.tensor([[4.],
                  [-7.]])

X = torch.inverse(A) @ B
print(X)

tensor([[-0.0909],
        [ 2.1818]])


In [15]:
import tensorflow as tf

In [ ]:
#tensorflow
A = tf.constant([[4., 2.],
                 [5., -3.]])

B = tf.constant([[4.],
                 [-7.]])

X = tf.linalg.inv(A) @ B
print(X)