# *MATRIKS MULTIPLICATION EXERCISES*

In [1]:
import torch

Baris ini berfungsi untuk memanggil library PyTorch. PyTorch adalah framework open-source yang sering digunakan untuk pengembangan Deep Learning.


In [2]:
M_q = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
M_q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Baris ini membuat sebuah Tensor 2-Dimensi (Matriks) berukuran $3 \times 3$ dengan nama variabel

M_q di bawahnya berfungsi untuk menampilkan isi dari matriks tersebut ke layar.

In [3]:
V_q = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
V_q

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

Kode ini membuat sebuah tensor awal berukuran 2 X 3 (2 baris, 3 kolom), namun langsung diikuti oleh fungsi

Fungsi .T (Transpose): Digunakan untuk menukar posisi baris menjadi kolom.

Hasil Akhir: Matriks yang tadinya 2
X 3 berubah menjadi 3 X 2.

Ini sangat penting dalam aljabar linear agar dimensi matriks sesuai untuk dikalikan dengan M_q

In [4]:
torch.matmul(M_q, V_q)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])

Fungsi torch.matmul() digunakan untuk melakukan perkalian matrik


 M_q berukuran ($3 \times 3$) dan v_q berukuran ($3 \times 2$).Karena jumlah kolom matriks pertama (3) sama dengan jumlah baris matriks kedua (3), maka perkalian ini sah/bisa dilakukan.

Komputer akan mengalikan baris dari M_q dengan kolom dari v_q satu per satu.

Output: Hasil akhirnya akan berupa matriks baru dengan ukuran $3 \times 2$.