24. Matrix Multiplication

soal 1

In [1]:
import numpy as np

In [18]:
A = np.array([[1, 3, 7],
              [4, 1, 9]])
B = np.array([[2],
              [4],
              [6]])

print("Matrix A:")
print(A)

print("\nVector B:")
print(B)

Matrix A:
[[1 3 7]
 [4 1 9]]

Vector B:
[[2]
 [4]
 [6]]


In [9]:
import torch

A_pt = torch.tensor([[1, 3, 7],
                     [4, 1, 9]])

B_pt = torch.tensor([[2],
                     [4],
                     [6]])
print("Matrix A_pt:")
print(A_pt)

print("\nVector B_pt:")
print(B_pt)

Matrix A_pt:
tensor([[1, 3, 7],
        [4, 1, 9]])

Vector B_pt:
tensor([[2],
        [4],
        [6]])


In [10]:
import tensorflow as tf
A_tf = tf.constant([[1, 3, 7],
                    [4, 1, 9]])

B_tf = tf.constant([[2],
                    [4],
                    [6]])

print("Matrix A_tf:")
print(A_tf)

print("\nVector b_tf:")
print(B_tf)

Matrix A_tf:
tf.Tensor(
[[1 3 7]
 [4 1 9]], shape=(2, 3), dtype=int32)

Vector b_tf:
tf.Tensor(
[[2]
 [4]
 [6]], shape=(3, 1), dtype=int32)


soal 2

In [20]:
A = np.array([[1, 3, 7],
              [4, 1, 9]])

B = np.array([[2],
              [4],
              [6]])

print("Ukuran matrix A:", A.shape)
print("Ukuran vector B:", B.shape)

Ukuran matrix A: (2, 3)
Ukuran vector B: (3, 1)


soal 3

In [28]:
import numpy as np

A = np.array([[1, 3, 7],
              [4, 1, 9]])

B = np.array([[2],
              [4],
              [6]])
np.dot(A, B)

array([[56],
       [66]])

In [32]:
import torch

A_pt = torch.tensor([[1, 3, 7],
                  [4, 1, 9]])

B_pt = torch.tensor([[2],
                  [4],
                  [6]])
torch.matmul(A_pt, B_pt)

tensor([[56],
        [66]])

In [34]:
import tensorflow as tf

A_tf = tf.constant([[1, 3, 7],
                    [4, 1, 9]])

B_tf = tf.constant([[2],
                    [4],
                    [6]])
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[56],
       [66]], dtype=int32)>

soal 4

In [39]:
import numpy as np

B = np.array([[1, 3, 7],
              [4, 1, 9],
              [6, 5, 2]])
B

array([[1, 3, 7],
       [4, 1, 9],
       [6, 5, 2]])

In [40]:
import torch

B = torch.tensor([[1, 3, 7],
                 [4, 1, 9],
                 [6, 5, 2]])
B

tensor([[1, 3, 7],
        [4, 1, 9],
        [6, 5, 2]])

In [42]:
import tensorflow as tf

B = tf.constant([[1, 3, 7],
                 [4, 1, 9],
                 [6, 5, 2]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 3, 7],
       [4, 1, 9],
       [6, 5, 2]], dtype=int32)>

soal 5


In [43]:
import numpy as np

A = np.array([[1, 3, 7],
              [4, 1, 9]])

B = np.array([[1, 3, 7],
              [4, 1, 9],
              [6, 5, 2]])

np.dot(A, B)

array([[55, 41, 48],
       [62, 58, 55]])

In [46]:
import torch

A_pt = torch.tensor([[1, 3, 7],
                    [4, 1, 9]])

B_pt = torch.tensor([[1, 3, 7],
                    [4, 1, 9],
                    [6, 5, 2]])

torch.matmul(A_pt, B_pt)

tensor([[55, 41, 48],
        [62, 58, 55]])

In [47]:
import tensorflow as tf

A_tf = tf.constant([[1, 3, 7],
                    [4, 1, 9]])

B_tf = tf.constant([[1, 3, 7],
                    [4, 1, 9],
                    [6, 5, 2]])

tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[55, 41, 48],
       [62, 58, 55]], dtype=int32)>

soal 6


In [55]:
import numpy as np

A = np.array([[1, 3, 7],
              [4, 1, 9]])

B = np.array([[1, 3, 7],
              [4, 1, 9],
              [6, 5, 2]])


In [56]:
 np.dot(A, B)

array([[55, 41, 48],
       [62, 58, 55]])

In [57]:
np.dot(B, A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

AB tidak sama dengan BA