# *SYMMETRIC AND IDENTITY MATRIKS*

In [9]:
import numpy as np

In [18]:
X_sym = np.array([[2, 5, 5], [0, 6, 1], [0, 0, 5]])
X_sym

array([[2, 5, 5],
       [0, 6, 1],
       [0, 0, 5]])

Baris ini membuat sebuah matriks $3 \times 3$ bernama X_sym.

In [11]:
X_sym.T

array([[5, 0, 5],
       [0, 5, 0],
       [0, 5, 5]])

Simbol .T digunakan untuk melakukan transpose, yaitu mengubah baris menjadi kolom dan kolom menjadi baris.

In [17]:
X_sym.T == X_sym

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [13]:
import torch

 Ini adalah fungsi dari library pytorch yang telah di impor sebagai torch. Fungsi ini digunakan untuk membuat sebuah tensor.

In [19]:
I = torch.tensor([[2, 5, 5], [0, 6, 1], [0, 0, 5]])
I

tensor([[2, 5, 5],
        [0, 6, 1],
        [0, 0, 5]])

 Variabel I di sini merepresentasikan matriks identitas ($I$).

In [15]:
x_pt = torch.tensor([2, 5, 5])
x_pt

tensor([2, 5, 5])

Ini adalah sebuah vektor kolom tensor 1D yang berisi tiga angka: 25, 2, dan 5.

In [16]:
torch.matmul(I, x_pt)

tensor([10, 50, 35])

matmul adalah singkatan dari matrix multiplication. Baris ini mengalikan Matriks Identitas (I) dengan vektor $x_{pt}$.Hasilnya: Sesuai hukum aljabar linear, setiap matriks atau vektor yang dikalikan dengan Matriks Identitas akan menghasilkan dirinya sendiri ($Ix = x$). Jadi, output dari kodingan ini tetaplah [25, 2, 5].