In [1]:
import numpy as np

MATRIKS DENGAN NUMPY,PYTORCH,DAN TENSORFLOW

In [7]:
# Buat Matrix X ukuran 2x3 menggunakan numpy
x = np.array([
    [1, 2, 3],
    [4, 5, 6]])

print("x (numpy):")
print(x)

x (numpy):
[[1 2 3]
 [4 5 6]]


In [8]:
import torch as pt

In [11]:
# Matrix x_pt ukuran 2x3 menggunkan pytorch
x_pt = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("x_pt (pytorch):")
print(x_pt)

x_pt (pytorch):
tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
import tensorflow as tf

In [20]:
# Matrix x_tf ukuran 2x3 menggunakan tensorflow
x_tf = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print("x_tf (tensorflow):")
print(x_tf)

x_tf (tensorflow):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


PERKALIAN

In [23]:
# lakukan perkalian matrix x dengan suatu skalar
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_np = k * X

print("Hasil NumPy (k * X):")
print(hasil_np)

Hasil NumPy (k * X):
[[ 3  6  9]
 [12 15 18]]


In [28]:
# lakukan perkalian matrix x_pt dengan suatu skalar

x_pt = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_pt = k * X_pt

print("hasil pytorch (k * x_pt):")
print(hasil_pt)

hasil pytorch (k * x_pt):
tensor([[ 3,  6,  9],
        [12, 15, 18]])


In [27]:
# lakukan perkalian matrix x_tf dengan suatu skalar

x_tf = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_tf = k * x_tf

print("Hasil TensorFlow (k * x_tf):")
print(hasil_tf)

Hasil TensorFlow (k * x_tf):
tf.Tensor(
[[ 3  6  9]
 [12 15 18]], shape=(2, 3), dtype=int32)


PENJUMLAHAN

In [30]:
# lakukan penjumlahan matrix x dengan suatu skalar

X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_np = X + k

print("Hasil NumPy (X + k):")
print(hasil_np)

Hasil NumPy (X + k):
[[4 5 6]
 [7 8 9]]


In [31]:
# lakukan penjumlahan matrix x_pt dengan suatu skalar
X_pt = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_pt = X_pt + k

print("Hasil PyTorch (X_pt + k):")
print(hasil_pt)

Hasil PyTorch (X_pt + k):
tensor([[4, 5, 6],
        [7, 8, 9]])


In [33]:
# lakukan penjumlahan matrix x_tf dengan suatu skalar

X_tf = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_tf = X_tf + k

print("Hasil TensorFlow (X_tf + k):")
print(hasil_tf)

Hasil TensorFlow (X_tf + k):
tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)


PENGURANGAN

In [35]:
# lakukan pengurangan matrix X dengan suatu skalar

X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_np = X - k

print("Hasil NumPy (X - k):")
print(hasil_np)

Hasil NumPy (X - k):
[[-2 -1  0]
 [ 1  2  3]]


In [37]:
# lakukan pengurangan matrix X_pt dengan suatu skalar

X_pt = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_pt = X_pt - k

print("Hasil PyTorch (X_pt - k):")
print(hasil_pt)

Hasil PyTorch (X_pt - k):
tensor([[-2, -1,  0],
        [ 1,  2,  3]])


In [38]:
# lakukan pengurangan matrix X_tf dengan suatu skalar

X_tf = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

k = 3
hasil_tf = X_tf - k

print("Hasil TensorFlow (X_tf - k):")
print(hasil_tf)

Hasil TensorFlow (X_tf - k):
tf.Tensor(
[[-2 -1  0]
 [ 1  2  3]], shape=(2, 3), dtype=int32)


2. buat matrix Y dengan ukuran 2x3 menggunakan numpy,pytorch,dan tensorflow

In [39]:
# Matrix Y ukuran 2x3 numpy
Y = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matrix Y (NumPy):")
print(Y)

Matrix Y (NumPy):
[[ 7  8  9]
 [10 11 12]]


In [41]:
# Matriks Y ukuran 2x3 pytorch

Y_pt = torch.tensor([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matrix Y (PyTorch):")
print(Y_pt)

Matrix Y (PyTorch):
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [42]:
# Matriks Y ukuran 2x3 tensorflow

Y_tf = tf.constant([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matrix Y (TensorFlow):")
print(Y_tf)

Matrix Y (TensorFlow):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


kalikan matrix X dengan Y,Y_pt,Y_tf

In [44]:
#Y

X = np.array([[1, 2, 3],
              [4, 5, 6]])

Y = np.array([[7, 8, 9],
              [10, 11, 12]])

hasil_np = X * Y
print(hasil_np)

[[ 7 16 27]
 [40 55 72]]


In [45]:
#Y_pt

X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

Y_pt = torch.tensor([[7, 8, 9],
                     [10, 11, 12]])

hasil_pt = X_pt * Y_pt
print(hasil_pt)

tensor([[ 7, 16, 27],
        [40, 55, 72]])


In [46]:
#Y_tf

X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])

Y_tf = tf.constant([[7, 8, 9],
                    [10, 11, 12]])

hasil_tf = X_tf * Y_tf
print(hasil_tf)

tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)
