# 1. buat matrix X dengan ukuran 2x3 menggunakan numpy

In [2]:
import numpy as np

In [6]:
X = np.array([[25, 1, 5], [0, 61, 60]])
X

array([[25,  1,  5],
       [ 0, 61, 60]])

# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch

In [7]:
import torch as pt

In [8]:
X_pt = pt.tensor([[25, 1, 5], [0, 61, 60]])
X_pt

tensor([[25,  1,  5],
        [ 0, 61, 60]])

# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [9]:
import tensorflow as tf

In [11]:
X_tf = tf.Variable ([[25, 1, 5], [0, 61, 60]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25,  1,  5],
       [ 0, 61, 60]], dtype=int32)>

# 2. lakukan transpose pada matrix X, X_pt dan X_tf

In [15]:
# transpose numpy
X.T

array([[25,  0],
       [ 1, 61],
       [ 5, 60]])

In [16]:
#transpose pytorch
X_pt.T

tensor([[25,  0],
        [ 1, 61],
        [ 5, 60]])

In [14]:
#transpose tensorflow
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25,  0],
       [ 1, 61],
       [ 5, 60]], dtype=int32)>