16. Tensor Reduction

soal 1

In [3]:
import numpy as np

In [6]:
X = np.array([[1, 3, 2], [2, 1, 1]])
X

array([[1, 3, 2],
       [2, 1, 1]])

In [14]:
X = np.array([1, 1, 1, 2, 2, 3])
print(np.sum(X))

10


In [16]:
import tensorflow as tf

In [17]:
X_tf = tf.Variable([[1, 3, 2], [2, 1, 1]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 2],
       [2, 1, 1]], dtype=int32)>

soal 2

In [18]:
import numpy as np

In [21]:
sum_np = np.sum(X)
print(np.sum(X))

10


In [3]:
import torch

In [37]:
X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]])
X_pt
print(sum(sum(row) for row in X_pt))

tensor(26)


In [11]:
import tensorflow as tf

In [38]:
X_tf = [[1, 7, 3],
        [4, 5, 6]]
X_tf = tf.Variable(X_tf)
X_tf


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 7, 3],
       [4, 5, 6]], dtype=int32)>

In [39]:
X = sum(sum(baris) for baris in X_tf)
print(X)

tf.Tensor(26, shape=(), dtype=int32)


soal 3

In [18]:
import numpy as np

In [40]:
X = np.array([[1, 7, 3],
              [4, 5, 6]])
X = np.sum(X, axis=1)
print(X)

[11 15]


In [23]:
import torch

In [41]:
X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]])

X = torch.sum(X_pt, dim=1)
print(X)

tensor([11, 15])


In [31]:
import tensorflow as tf

In [42]:
X_tf = tf.constant([[1, 7, 3],
                    [4, 5, 6]])

X_tf = tf.reduce_sum(X_tf, axis=1)
print(X_tf)

tf.Tensor([11 15], shape=(2,), dtype=int32)


soal 4

In [33]:
import numpy as np


In [43]:
X = np.array([[1, 7, 3],
              [4, 5, 6]])

X = np.sum(X, axis=0)
print(X)

[ 5 12  9]


In [35]:
import torch

In [44]:
X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]])

X_pt = torch.sum(X_pt, dim=0)
print(X_pt)

tensor([ 5, 12,  9])


In [45]:
import tensorflow as tf

In [46]:
X_tf = tf.constant([[1, 7, 3],
                    [4, 5, 6]])

X_tf = tf.reduce_sum(X_tf, axis=0)
print(X_tf)

tf.Tensor([ 5 12  9], shape=(3,), dtype=int32)


soal 5

In [47]:
import numpy as np

X = np.array([[1, 7, 3],
              [4, 5, 6]])

X_min = np.min(X)
print(X_min)

1


In [49]:
import torch

X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]])

X_pt_min = torch.min(X_pt)
print(X_pt_min)

tensor(1)


In [50]:
import tensorflow as tf

X_tf = tf.constant([[1, 7, 3],
                    [4, 5, 6]])

X_tf_min = tf.reduce_min(X_tf)
print(X_tf_min)

tf.Tensor(1, shape=(), dtype=int32)


In [51]:
import numpy as np

X = np.array([[1, 7, 3],
              [4, 5, 6]])

X_max = np.max(X)
print(X_max)

7


In [52]:
import torch

X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]])

X_pt_max = torch.max(X_pt)
print(X_pt_max)

tensor(7)


In [53]:
import tensorflow as tf

X_tf = tf.constant([[1, 7, 3],
                    [4, 5, 6]])

X_tf_max = tf.reduce_max(X_tf)
print(X_tf_max)

tf.Tensor(7, shape=(), dtype=int32)


In [54]:
import numpy as np

X = np.array([[1, 7, 3],
              [4, 5, 6]])

rata_rata = np.mean(X)
print(rata_rata)

4.333333333333333


In [55]:
import torch

X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]], dtype=torch.float32)

rata_rata = torch.mean(X_pt)
print(rata_rata)

tensor(4.3333)


In [56]:
import tensorflow as tf

X_tf = tf.constant([[1, 7, 3],
                    [4, 5, 6]], dtype=tf.float32)

rata_rata = tf.reduce_mean(X_tf)
print(rata_rata)

tf.Tensor(4.3333335, shape=(), dtype=float32)


soal 6

In [57]:
import numpy as np

X = np.array([[1, 7, 3],
              [4, 5, 6]])

X = np.prod(X)
print(X)

2520


In [58]:
import torch

X_pt = torch.tensor([[1, 7, 3],
                     [4, 5, 6]])

X_pt = torch.prod(X_pt)
print(X_pt)

tensor(2520)


In [59]:
import tensorflow as tf

X_tf = tf.constant([[1, 7, 3],
                    [4, 5, 6]])

X_tf = tf.reduce_prod(X_tf)
print(X_tf)

tf.Tensor(2520, shape=(), dtype=int32)
